version: "3.8"

services:
  comfyui:
    image: pionai/runpod-worker-comfy-m2m:0109
    container_name: comfyui-worker
    runtime: nvidia 
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - SERVE_API_LOCALLY=true
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
    ports:
      - "54310:8000"
      - "54311:8188"
    volumes:
      - ./data/comfyui/output:/comfyui/output
      - ./data/runpod-volume:/runpod-volume
